site:
  title: ITIL 4 Foundation - Документация
  start_page: itil4-foundation::index.adoc  
  url: https://eustatos.github.io/itil4-foundation-ru/

content:
  sources:
    - url: ./
      branches: [main]
      start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

asciidoc:
  attributes:
    experimental: ''
    sectanchors: ''
    toc: macro
    toclevels: 3
    source-highlighter: highlightjs
    highlightjs-theme: github
    icons: font
    idprefix: ''
    idseparator: '-'
    kroki-server-url: 'https://kroki.io'
    kroki-fetch-diagram: ''
    plantuml-server-url: 'https://www.plantuml.com/plantuml'
  extensions:
    - asciidoctor-kroki